apiVersion: v1
kind: Namespace
metadata:
  name: alert-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-manager
  labels:
    app: alert-manager
  namespace: alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-manager
  template:
    metadata:
      labels:
        app: alert-manager
    spec:
      containers:
      - name: alert-manager
        image: akashj08/alert-manager:v1  # Replace with your Docker image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: APP_PORT
          value: "5000"
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: alert-manager-secrets
              key: slack_webhook_url
        - name: PROMETHEUS_URL
          value: "http://prometheus-server.monitor"  # Update this to your Prometheus server URL
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Secret
metadata:
  name: alert-manager-secrets
  namespace: alert-manager
  labels:
    app: alert-manager
type: Opaque
data:
  slack_webhook_url: "XXXXXXXXXX"  # Replace with the base64-encoded Slack Webhook URL : https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK

---
apiVersion: v1
kind: Service
metadata:
  name: alert-manager
  namespace: alert-manager
  labels:
    app: alert-manager
spec:
  selector:
    app: alert-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: ClusterIP
